In [2]:
import torch
import numpy as np

In [3]:
data = [[1, 2], [3, 4]]
data_tensor = torch.tensor(data)
print(data_tensor, type(data_tensor))

tensor([[ 1,  2],
        [ 3,  4]]) <class 'torch.Tensor'>


In [4]:
data = [[1, 2], [3, 4], [5, 6]]
np_data = np.array(data)
print(np_data, type(np_data))
np_data_tensor = torch.from_numpy(np_data)
print(np_data_tensor, type(np_data_tensor))
print("this is test torch load")

[[1 2]
 [3 4]
 [5 6]] <class 'numpy.ndarray'>
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6]]) <class 'torch.Tensor'>
this is test torch load


In [5]:
torch.zeros(5)

tensor([ 0.,  0.,  0.,  0.,  0.])

In [6]:
torch.ones(2, 2)

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [7]:
torch.rand(3, 3, 3)

tensor([[[ 0.2963,  0.7773,  0.7948],
         [ 0.0040,  0.7397,  0.8019],
         [ 0.5143,  0.7119,  0.4376]],

        [[ 0.2467,  0.4381,  0.1018],
         [ 0.1115,  0.7927,  0.1984],
         [ 0.0982,  0.3449,  0.1232]],

        [[ 0.9597,  0.8919,  0.4222],
         [ 0.0990,  0.6434,  0.1352],
         [ 0.1158,  0.9963,  0.4330]]])

In [9]:
zero_tensor = torch.zeros(3, 3)
ones_like_zeros = torch.ones_like(zero_tensor)

print(zero_tensor.shape, ones_like_zeros.shape)

torch.Size([3, 3]) torch.Size([3, 3])


In [13]:
zero_tensor[0]

tensor([ 0.,  0.,  0.])

In [38]:
tmp = ones_like_zeros[:, 0:1] * 2
print(tmp)

tensor([[ 4.],
        [ 4.],
        [ 4.]])


In [15]:
x = ones_like_zeros.detach()
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])


In [34]:
print(x[0:3,0:3] * 5)
print(x)


tensor([[ 5.,  5.,  5.],
        [ 5.,  5.,  5.],
        [ 5.,  5.,  5.]])
tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])


In [ ]:
rand1 = torch.rand(5)
rand2 = torch.rand(5)
torch.matmul(rand1, rand2)

In [ ]:
rand1 = torch.rand(5, 5)
rand2 = torch.rand(5, 5)
torch.matmul(rand1, rand2)